name: Deploy Gitee Pages

on:
  push:
    tags:
      - v*
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Wait Gitee Sync
        run: sleep 3m
        shell: bash

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: RootWater
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: RootWater/nice-fns
          branch: dev
          directory: website