name: Deploy Gitee Pages

on:
  push:
    tags:
      - release/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: RootWater
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: RootWater/nice-fns
          branch: dev
          directory: website