name: syncToGitee
on:
  push:
    branches:
      - dev
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts

      - name: install pnpm
        run: npm i pnpm@latest -g

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: install dependencies
        run: pnpm install

      - name: build docs
        run: pnpm docs:build

      - name: mirror with force push (git push -f)
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/l246804
          dst: gitee/RootWater
          dst_key: '${{ secrets.GITEE_PRIVATE_KEY }}'
          dst_token: '${{ secrets.GITEE_TOKEN }}'
          static_list: nice-fns
          force_update: true
          debug: true

      - name: deploy pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: RootWater
          gitee-password: '${{ secrets.GITEE_PASSWORD }}'
          gitee-repo: RootWater/nice-fns
          branch: dev
          directory: website
